version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: lexia-postgres
    environment:
      POSTGRES_DB: lexia_dev
      POSTGRES_USER: lexia
      POSTGRES_PASSWORD: lexia123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
