databases:
  - name: lexia-database
    databaseName: lexia_production
    user: lexia_user
    plan: free

services:
  - type: web
    name: lexia-onboarding
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: lexia-database
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: https://lexia-onboarding.onrender.com
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: SEED_PRODUCTION
        value: "true"
    healthCheckPath: /
    autoDeploy: true
    buildFilter:
      paths:
        - app/**
        - components/**
        - lib/**
        - prisma/**
        - public/**
        - package.json
        - package-lock.json
        - next.config.js
        - tailwind.config.js
        - tsconfig.json
